name: Rustix Auto Restart

on:
  schedule:
    # 每小时运行一次
    - cron: '0 */1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: python rustix.py
